### ISSUE TITLE
Update to 4.23 or 4.24

### ISSUE THREAD

**Issue by SemiRealProductions** [How2Compute/Socketer#1]
Will there be an update to 4.23 or 4.24?

**Comment by How2Compute** [comment]
Hi SemiRealProductions,

Thanks for opening up this issue! I'm afraid that I have been incredibly busy over the last few months, but I finally got around to updating the plugin for later versions of Unreal Engine 4.

With the [latest release](https://github.com/How2Compute/Socketer/releases/tag/v0.4-UE425) (v0.4 at the time of writing) come various improvements, and support for Unreal Engine 4.25.

I believe this should resolve your issue, and I am closing your issue to relfect this. If you'd still like to see a (precompiled) version for one of the aforementioned versions of Unreal Engine, then please don't hesitate to re-open this issue with a comment, and I'll see what I can do.

-HowToCompute
