### ISSUE TITLE
fail to compile bp

### ISSUE THREAD

**Issue by rickrs** [How2Compute/Socketer#3]
hi there, where i found a documentation about the construction of bp? cause, in u video u only show the BP and dont explain the variables.

can u share a demo project? i get this error :  Set ServConnection  was pruned because its Exec pin is not connected, the connected value is not available and will instead be read as default 

here my bp ty

![image](https://user-images.githubusercontent.com/1570077/123120983-2aab3180-d41b-11eb-85df-d9d569b592c2.png)
![image](https://user-images.githubusercontent.com/1570077/123121179-55958580-d41b-11eb-974c-7e513f827e36.png)

**Comment by How2Compute** [comment]
Hi rickjs,

I'm afraid that I don't currently have an example project ready, but it looks like you're trying to use your variable without actually setting it. You should be able to resolve it by breaking your connection between the _Connect to a TCP server_ and the _Branch_ node, and then connecting your _SET_ node in between them. I've tried to share this in the screenshot below:

![BP Suggestions](https://i.imgur.com/YlNdNdt.png)

I hope this helps, and let me know if this resolves the issue for you!

\- HowToCompute
